[package]
name = "lunarlander"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.8"
rand = "0.8.5"
cgmath = "0.18.0"
kira = "0.9.3"
